version: '3'
services:
  first-container:
    build:
      context: .
      dockerfile: Dockerfile
  second-container:
    image: nginx
    ports:
      - "80:8080"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - first-container


# services:
#   nginx:
#     image: nginx:latest
#     ports:
#       - "8080:80" 
#     restart: unless-stopped
#     depends_on:
#       - first_container
#     container_name: nginx
#       - default

#   first_container:
#     build:
#       context: .
#       dockerfile: ./part-5/Dockerfile
#     restart: unless-stopped
#     ports:
#       - "81:81"
#     container_name: part_5
    