FROM nginx:latest

COPY ./hello.c /home/dockle/

COPY ./nginx.conf /etc/nginx/nginx.conf 

RUN useradd -g daemon -d /home/dockle -m -s /bin/bash dockle && \
    chown -R dockle:daemon /var/cache/nginx/ /var/run/ /var/log/nginx/ && \
    apt update && \
    apt install -y gcc libfcgi-dev spawn-fcgi && \
    gcc -o /home/dockle/hello /home/dockle/hello.c -lfcgi && apt-get clean && \
    rm -rf /var/lib/apt/lists/*

USER dockle

WORKDIR /home/dockle

CMD ["/bin/bash", "-c", "nginx -g 'daemon off;' | nginx -s reload | spawn-fcgi -p 8080 -n /home/dockle/hello"]